"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ibooks_highlights_exporter.py']
DATA_FILES = [('templates', ['templates/open_mindmap.xml'])]
APP_NAME = "iBooksHighlightsExporter"
OPTIONS = {'argv_emulation': True,
           'iconfile': './iBooksExporter.icns',
           'includes': ['jinja2', 'six', 'urllib', 'packaging', 'packaging.version',
             'packaging.specifiers', 'packaging.requirements', 'pkg_resources'],
           'plist': {
                'CFBundleName': APP_NAME,
                'CFBundleDisplayName': APP_NAME,
                'CFBundleGetInfoString': "Exporting iBooks highlights into .opml file format",
                'CFBundleIdentifier': "com.ibooksutils.ibookshighlightsexport",
                'CFBundleVersion': '1001',
                'CFBundleShortVersionString': '1.0',
               'NSHumanReadableCopyright': 'Copyright 2017'
            }}

setup(
    name='iBooks highlights export',
    version='1.0',
    description='Simple GUI app to export iBooks highlights as a Mind Map',
    author='Hiyorimi',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'jinja2'],
)
